### PR TITLE
doing fix for survey to test generator

### PR DESCRIPTION
**Pull request by vsoch**
This will be a PR to fix the bug with the numeric field, @earcanal would you like to test? I've prepared and pushed a development container:

```bash
docker pull vanessa/survey-generator:dev
```
When done, this will be released as tags `0.0.2` and `latest`

### CODE REVIEW

**Comment by earcanal** [comment]
As a reminder to myself, to pull then generate I did

`docker run -v $PWD:vanessa/survey-generator:dev start --force`

This works, but I'm a bit twitchy about unforeseen regressions in existing surveys that use `numeric`.  I suggested a new `real` type to be conservative about this.  Anyway, I'll leave that decision up to you.

Is this warning a concern?

```
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Writing output files to /data/index.html
...
```

I would make the warning `<span class="mdl-textfield__error">Please enter an integer or real number.</span>`, as the regex allows either.

**Comment by vsoch** [comment]
Versioning, and old surveys, maintaining them, is your burden, I just build the software that gives you versions to do this :) These types (numeric, text) are defined for the browser, you can't just make them up! See --> https://www.w3schools.com/html/html_form_input_types.asp

I think the warning is fine - most of these numbers we are dealing with aren't going beyond one or two decimals, at most.

I've updated the error message.

**Comment by vsoch** [comment]
okay merging, will release as 0.0.2.

**Comment by earcanal** [comment]
Why are `0.0.2` and `latest` different sizes?

https://hub.docker.com/r/vanessa/survey-generator/tags/

**Comment by vsoch** [comment]
because I forgot to push latest, lol. This is why CI should be doing this and not manual me :)

**Comment by earcanal** [comment]
HTML is good in `latest`, but there's still a warning.  Is that OK?

```
$ docker run -v $PWD:/data vanessa/survey-generator start --force
Writing output files to /data/index.html
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
...
```

**Pull request merged**
