### PR TITLE
adding likert class

### PR DESCRIPTION
**Pull request by vsoch**
hey @earcanal here is the changes to test! Let me build you a container to test quickly...

### CODE REVIEW

**Comment by vsoch** [comment]
okay @earcanal here is your testing container - note I'm using this as opportunity to move the repo to expfactory organization

https://hub.docker.com/r/expfactory/survey-generator/tags/

You will want to try the tag "0.0.3rc"  that is going to be deployed from this PR (after you test!)

```
$ docker run -v $PWD:/data expfactory/survey-generator:0.0.3rc start
```
I think that's the command? From an experiment directory... it's been a while lol.

**Comment by vsoch** [comment]
And docs change, when you approve, will be merged here: https://github.com/expfactory/expfactory.github.io/pull/4/files

**Comment by earcanal** [comment]
Almost.  The `likert` class needs to be on the `p`.  It's currently on the `label` inside the `p`:

```
<p id="dass-21_1_options">I found it hard to wind down</p>
<label class="mdl-radio mdl-js-radio mdl-js-ripple-effect likert" for="option-dass-21_1_0">
```

**Comment by vsoch** [comment]
heh, oups! Check it out now?

**Comment by earcanal** [comment]
Do I need to wait for the container to rebuild?

**Comment by vsoch** [comment]
Nope but you need to pull it again first, it has the same name as the one in your computer. If you just run it will use the old one.

**Comment by earcanal** [comment]
(Note to self `docker pull expfactory/survey-generator:0.0.3rc`.)

Looks good to me (grey lines in all the right places)!

**Comment by vsoch** [comment]
okay pushed! Thanks @earcanal

**Comment by earcanal** [comment]
Should the [docs]( https://expfactory.github.io/integration-surveys) now refer to `expfactory/survey-generator` rather than `vanessa/survey-generator`?

**Comment by vsoch** [comment]
oh yeah just forgot to merge that PR, thanks for the reminder!

**Pull request merged**
